"""Meal plan models: slots, portions, meals, and the scheduled plan.

Portions are stored on the *purchased* basis (same grams the basket counts),
so scheduled + leftover + pantry carryover always equals what was bought.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from models.food import Food, Nutrients


class MealSlot(str, Enum):
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"


SLOT_ORDER: tuple[MealSlot, ...] = (MealSlot.BREAKFAST, MealSlot.LUNCH, MealSlot.DINNER)

SLOT_KCAL_SHARE: dict[MealSlot, float] = {
    MealSlot.BREAKFAST: 0.25,
    MealSlot.LUNCH: 0.35,
    MealSlot.DINNER: 0.40,
}

# Per-person calorie share ranges by slot (recipe-first validation). Slot targets
# are soft; the per-person daily total is the hard constraint (see daily_validator).
SLOT_KCAL_RANGE: dict[MealSlot, tuple[float, float]] = {
    MealSlot.BREAKFAST: (0.20, 0.30),
    MealSlot.LUNCH: (0.30, 0.35),
    MealSlot.DINNER: (0.30, 0.40),
}

DAILY_KCAL_TOLERANCE = 0.10

# Meal provenance. "recipe" = generated by the recipe-first engine from a real
# catalog recipe; "legacy_template" = produced by the retired template scheduler
# (kept only behind the dev flag) or migrated from an old saved plan.
SOURCE_RECIPE = "recipe"
SOURCE_LEGACY = "legacy_template"

SLOT_LABELS: dict[MealSlot, str] = {
    MealSlot.BREAKFAST: "Breakfast",
    MealSlot.LUNCH: "Lunch",
    MealSlot.DINNER: "Dinner",
}


@dataclass(frozen=True)
class MealPortion:
    """One food's share of a meal, in purchased grams.

    ``cooked_grams`` is a display-only estimate for dry foods (rice, pasta,
    lentils, ...) so portion labels read as plate weights.

    ``component_kind`` keeps main/side provenance after a side recipe's
    ingredients are folded into the single portions list: a batchable main
    doubles while a fresh side does not, main vs side directions scale
    independently, leftovers replenish the right part, and swapping a side
    removes only its portions. ``source_recipe_id`` records which recipe the
    portion came from.
    """

    food: Food
    grams: float
    cooked_grams: float | None = None
    source_recipe_id: str | None = None
    component_kind: str = "main"  # "main" | "side"

    @property
    def nutrients(self) -> Nutrients:
        # Same basis as BasketItem.nutrients, so consumed + carryover == purchased.
        return self.food.nutrients_per_purchased_100g().scaled(self.grams / 100.0)

    @property
    def kcal(self) -> float:
        return self.nutrients.calories_kcal


@dataclass(frozen=True)
class Meal:
    slot: MealSlot
    # Legacy template/recipe identifier. Non-empty only for meals produced by the
    # retired template scheduler or migrated from an old saved plan; the
    # recipe-first engine leaves it "" and uses ``recipe_id`` instead.
    template_id: str
    name: str
    portions: tuple[MealPortion, ...]
    # Recipe-first identity: a real catalog recipe id (only ever an id that
    # resolves in the Recipe Catalog), the household servings the portions cover,
    # and an optional verified side recipe folded into ``portions``.
    recipe_id: str | None = None
    source_kind: str = SOURCE_LEGACY
    servings: float = 0.0
    side_recipe_id: str | None = None
    side_servings: float = 0.0
    is_leftover: bool = False
    batch_id: str | None = None
    # Set when this meal IS a scheduled prepared leftover (ready meal): it
    # draws zero raw ingredients and eating it consumes the referenced record.
    prepared_leftover_id: str | None = None

    @property
    def nutrients(self) -> Nutrients:
        total = Nutrients()
        for portion in self.portions:
            total = total.plus(portion.nutrients)
        return total

    @property
    def kcal(self) -> float:
        return self.nutrients.calories_kcal

    @property
    def per_person_kcal(self) -> float | None:
        """Calories per person; None for legacy meals with unknown servings
        (the UI then falls back to the whole-household total)."""
        if self.servings and self.servings > 0:
            return self.nutrients.calories_kcal / self.servings
        return None

    def portions_for(self, component_kind: str) -> tuple[MealPortion, ...]:
        return tuple(p for p in self.portions if p.component_kind == component_kind)


@dataclass(frozen=True)
class DayPlan:
    """One day's meals; an infeasible slot is simply absent (at most 3)."""

    day_index: int
    meals: tuple[Meal, ...]

    def meal_for(self, slot: MealSlot) -> Meal | None:
        for meal in self.meals:
            if meal.slot is slot:
                return meal
        return None


@dataclass(frozen=True)
class MealPlan:
    days: tuple[DayPlan, ...]
    pantry_carryover: dict[str, float] = field(default_factory=dict)  # food_id -> grams
    consumed_totals: Nutrients = field(default_factory=Nutrients)
    horizon_days: int = 7
